name: Dependency cruiser

on: [pull_request]

jobs:
  depcruise-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run build:tailwind
      - run: npm run depcruise
